# Generated by Django 2.0 on 2018-06-12 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageant', '0005_auto_20180612_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
