# Generated by Django 2.0 on 2018-06-12 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageant', '0006_category_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('order',), 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='candidate',
            name='title',
            field=models.TextField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
