# Generated by Django 2.0 on 2018-06-13 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageant', '0007_auto_20180612_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='id',
            field=models.TextField(max_length=5, primary_key=True, serialize=False, unique=True),
        ),
    ]
