# Generated by Django 2.0 on 2018-06-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageant', '0009_talent'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='weight',
            field=models.FloatField(default=0.2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='talent',
            name='weight',
            field=models.FloatField(default=0.2),
            preserve_default=False,
        ),
    ]
