# Generated by Django 2.0 on 2018-06-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageant', '0012_auto_20180613_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='final',
            name='rank',
            field=models.IntegerField(),
        ),
    ]
