# Generated by Django 2.0 on 2018-06-13 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pageant', '0013_auto_20180613_1350'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='final',
            unique_together={('judge', 'rank'), ('candidate', 'judge')},
        ),
    ]
