# Generated by Django 2.0 on 2018-06-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageant', '0014_auto_20180613_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='final',
            name='rank',
            field=models.FloatField(),
        ),
    ]
