# Generated by Django 2.0 on 2018-06-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageant', '0015_auto_20180613_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='finalist',
            field=models.BooleanField(default=False),
        ),
    ]
